### ISSUE TITLE
chunk-manifest-webpack-plugin should be a peerDependency

### ISSUE THREAD

**Issue by sunyang713** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#12]
`chunk-manifest-webpack-plugin` should be a peerDependency. As a nested dependency, the maintainer of this project would need to routinely check and update this project's package.json whenever `chunk-manifest-webpack-plugin` updates.

**Comment by jouni-kantola** [comment]
@sunyang713: I appreciate your concern but I'll let semver do it's job. Also, for the default workflow `chunk-manifest-webpack-plugin` *is* a dependency.

Thank you for reaching out.

**Comment by sunyang713** [comment]
okay, understood. thanks for responding.
