### ISSUE TITLE
Update chunk-manifest-webpack-plugin

### ISSUE THREAD

**Issue by DimitarNestorov** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#13]

**Comment by rjdlee** [comment]
👎

**Comment by jouni-kantola** [comment]
This is handled in https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/pull/17

@rjdlee why do you think `chunk-manifest-webpack-plugin` shouldn't be updated?

**Comment by DimitarNestorov** [comment]
Might as well fork it, cause the creators are SoundCloud 😄

**Comment by jouni-kantola** [comment]
I just published [2.0.0 to npm](https://www.npmjs.com/package/inline-chunk-manifest-html-webpack-plugin) which forks [chunk-manifest-webpack-plugin](https://github.com/soundcloud/chunk-manifest-webpack-plugin/). In the PR webpack 2/3 is set as peer dependency.
