### ISSUE TITLE
Can you show me some full examples

### ISSUE THREAD

**Issue by tonyzheng121** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#15]
I try in my project, but it doesn't work. Error happen like below, it don't know why

![image](https://user-images.githubusercontent.com/6621024/28409661-d5585054-6d6d-11e7-9ed4-29e1b77c830f.png)

**Comment by jouni-kantola** [comment]
You need to be a bit more detailed for me to give any good suggestions.

Here's an example where the plugin's used:
https://github.com/jouni-kantola/webpack-output-by-build-type/blob/master/webpack.config.js
