### ISSUE TITLE
Update package.json to allow for webpack ^3.0.0

### ISSUE THREAD

**Issue by csentis** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#16]
With webpack ^3.0.0 installed, the dependency of this plugin on `"chunk-manifest-webpack-plugin": "~1.0.0"` (as listed in `package.json`) results in a yarn warning:

`warning "chunk-manifest-webpack-plugin@1.0.0" has incorrect peer dependency "webpack@^2.0.0".`

Will you kindly consider whether an update of `package.json` is doable?

**Comment by chrisui** [comment]
`chunk-manifest-webpack-plugin` is the issue here. They recently merged and published a fix for this.

We should update the dependency of that package to `^1.1.1`.

https://github.com/soundcloud/chunk-manifest-webpack-plugin/pull/40

**Comment by chrisui** [comment]
Have created a pull request with this change here: https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/pull/17

Would be great to get this merged and published asap since this is a blocker for upgrading webpack. Thanks!

cc @csentis @jouni-kantola

**Comment by csentis** [comment]
@chrisui Thanks mate!

**Comment by jouni-kantola** [comment]
In this repo https://github.com/jouni-kantola/webpack-output-by-build-type I upgraded to:
- webpack@3.4.1
- webpack-dev-server@2.6.1
- html-webpack-plugin@2.29.0

When I build everything works as expected, with the chunk manifest inlined by `html-webpack-plugin`.
@chrisui: Can you explain why this is an issue for upgrading to webpack 3?

Here's the branch if you want to try it out yourselves:
https://github.com/jouni-kantola/webpack-output-by-build-type/tree/webpack-3

However, if I upgrade `chunk-manifest-webpack-plugin` to `1.1.2` as dependency for `inline-chunk-manifest-html-webpack-plugin` inlining of the webpack runtime itself fails.

**Comment by csentis** [comment]
Thanks, @jouni-kantola for picking this up!

Could the breaking you experience be related to [this issue](https://github.com/soundcloud/chunk-manifest-webpack-plugin/issues/47) in `chunk-manifest-webpack-plugin`?

**Comment by jouni-kantola** [comment]
Not quite sure, I got to debug. Haven't had time to investigate (just got twins ⏲ ). The JSON file itself can already be dropped by passing `dropAsset` to `inline-chunk-manifest-html-webpack-plugin`

**Comment by jouni-kantola** [comment]
If I comment out https://github.com/soundcloud/chunk-manifest-webpack-plugin/blob/master/lib/ChunkManifestPlugin.js#L42 everything works fine. I'll see if I can work around it.

**Comment by chrisui** [comment]
> @chrisui: Can you explain why this is an issue for upgrading to webpack 3?

NPM install (with shrinkwrap) will complain about invalid peer dependencies and is sadly a failing process.

**Comment by jouni-kantola** [comment]
This is resolved now as of closing PR https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/pull/18. Read more here:
https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/pull/17#issuecomment-340181283

Version [2.0.0 published to npm](https://www.npmjs.com/package/inline-chunk-manifest-html-webpack-plugin).
