### ISSUE TITLE
Leaves behind an unused manifest file

### ISSUE THREAD

**Issue by outdooricon** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#5]
Love this plugin!! Thank you for making this. I just noticed one issue and that is it leaves behind the manifest.json file in the build directory. It would really nice if it cleaned up the file after it had injected the contents into index.

**Comment by jouni-kantola** [comment]
Great that it comes to use, @outdooricon!

I've added the config option `{ dropAsset: true }` (defaults to `false`). Instructions in readme are updated.

Published to npm as v0.2.1.

**Comment by outdooricon** [comment]
awesome, thank you!
