### ISSUE TITLE
Need option to disable 'chunk-manifest-webpack-plugin'

### ISSUE THREAD

**Issue by bat-bold** [jouni-kantola/inline-chunk-manifest-html-webpack-plugin#8]
[chunk-manifest-webpack-plugin](https://github.com/soundcloud/chunk-manifest-webpack-plugin) doesn't provide enough information(only chunks).
I need to use [webpack-manifest-plugin](https://github.com/danethurber/webpack-manifest-plugin).

Since inline-chunk-manifest-html-webpack-plugin@1.0.0
```
const ManifestPlugin = require ( 'webpack-manifest-plugin' );
const InlineChunkManifestHtmlWebpackPlugin = require ( 'inline-chunk-manifest-html-webpack-plugin' );

...
plugins: [
    new ManifestPlugin ( { publicPath } ),
    new InlineChunkManifestHtmlWebpackPlugin ( { manifestVariable: 'manifest' } ),
  ]
...
```
Using like above  makes `System.import('filename')` fail. 

Maybe providing necessary plugin from a user like before is better idea?

**Comment by jouni-kantola** [comment]
@Batbold-Gansukh: Thank you for reaching out. For now, use the version 0.2.1 and I'll compare `webpack-manifest-plugin` with `chunk-manifest-webpack-plugin`.

**Comment by jouni-kantola** [comment]
Can you explain the scenario where you need to use `webpack-manifest-plugin`, what is the output you need?

I myself am using `inline-chunk-manifest-html-webpack-plugin` here https://github.com/jouni-kantola/webpack-output-by-build-type, and it works fine with dynamic imports.

The reason why I'm asking is because `webpack-manifest-plugin` seems to output all assets, and I cannot really see why it would be necessary to extract anything else than chunks you'd need for dynamic imports.

**Comment by jouni-kantola** [comment]
However, I hadn't really thought of the idea before to consider any plugin generating a chunk manifest (manifest.json) as a dependency.

I'll update the `inline-chunk-manifest-html-webpack-plugin` to override the default behaviour with something like this:
```javascript
manifestPlugins: [ new ManifestPlugin(/*args*/) ]
```

**Comment by bat-bold** [comment]
Thanks for response.

I'm using `inline-chunk-manifest-html-webpack-plugin` to develop React and Typescript app.
Only small part of my app uses big jquery library and I'm loading its dependencies manually from code not by dynamic import. Also I want to process this library's assets through webpack. To do that I'm using `webpack-manifest-plugin`.

Using `webpack-manifest-plugin` with `inline-chunk-manifest-html-webpack-plugin@1.0.0` does output `manifest.json` containing all assets. But breaks dynamic imports in other parts of the app.

I'm currently using the `1.0.0` by modifying the plugin code from `node_modules` like below:
```
this.plugins = [
      //new ChunkManifestPlugin({
      //  filename: this.manifestFilename,
      //  manifestVariable: this.manifestVariable
      //})
    ];
```
That is why I thinking maybe a user providing a plugin that generates `manifest.json` is better idea.

**Comment by jouni-kantola** [comment]
@Batbold-Gansukh: If you update your `package.json` to reference:
```"inline-chunk-manifest-html-webpack-plugin": "https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin.git#f3a0379c769697b4476128a150aeb6b4ab30244a"```

Then update your `webpack.config.js` to this:
```javascript
new InlineChunkManifestHtmlWebpackPlugin({
    manifestPlugins: [
      new WebpackManifestPlugin()
    ],
    manifestVariable: "manifest"
  }),
// example below, match how your html-webpack-config looks
  new HtmlWebpackPlugin({
    template: "./tmpl/index.ejs"
  })
```

As a more bruteforce version you can use:
```javascript
  new WebpackManifestPlugin(),
  new InlineChunkManifestHtmlWebpackPlugin({
     manifestVariable: "manifest",
     extractManifest: false
  }),
  // example below, match how your html-webpack-config looks
  new HtmlWebpackPlugin({
    template: "./tmpl/index.ejs"
  })
```

Both should work as you expect. Please get back to me and I'll:
- merge the PR
- close this issue
- publish a v1.1.0 to NPM

**Comment by jouni-kantola** [comment]
You have the instructions in the readme here (in the bottom):
https://github.com/jouni-kantola/inline-chunk-manifest-html-webpack-plugin/blob/56cb5a0efc89443f4a8fe0be197c6a365a9df55d/README.md

**Comment by bat-bold** [comment]
Thank you for your time.

Both version working without a problem. 👍

**Comment by jouni-kantola** [comment]
Thanks for reaching out. I'm glad the plugin just got even more versatile 👍 

I'll make a note here when I've pushed a new release.

**Comment by jouni-kantola** [comment]
`v1.1.0` now published to npm.
